services:
  - type: web
    name: quiz-ai-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true 